# Nixpacks configuration for Railway deployment
# Installs all required dependencies for Puppeteer/Chromium

[phases.setup]
# System packages required for Puppeteer to run headless Chrome
# Updated for Ubuntu Noble (24.04) compatibility
aptPkgs = [
    'fonts-liberation',
    'libappindicator3-1',
    'libasound2t64',
    'libatk-bridge2.0-0t64',
    'libatk1.0-0t64',
    'libgbm1',
    'libgtk-3-0t64',
    'libnspr4',
    'libnss3',
    'libx11-xcb1',
    'libxcomposite1',
    'libxcursor1',
    'libxdamage1',
    'libxfixes3',
    'libxi6',
    'libxrandr2',
    'libxss1',
    'libxtst6',
    'xdg-utils',
    'ca-certificates',
    'wget'
]

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'node dist/server.js'
