# Railway.toml - Alternative configuration using TOML format
# Use this if you prefer TOML over JSON

[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 100
startCommand = "node dist/server.js"

# For Docker Image Deployment
# Uncomment the following if deploying from Docker Hub image:
# [build]
# dockerfilePath = "Dockerfile"
#
# Or for external image:
# [deploy]
# image = "luizeof/wppconnect:latest"
