# Railway.toml - Docker Image Deployment
# Using Dockerfile to pull pre-built luizeof/wppconnect image

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 100
